sudo: false
language: python
env: RUNNER=travis
python:
  - "2.7"
  # - "3.2"
addons:
  postgresql: "9.3"
install: "pip install -r requirements.txt --download-cache $HOME/.pip-cache"
before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
script: python resultsrecorder/manage.py test --noinput
notifications:
  slack: democracyclub:XCf7jPrqCZViINfxYiL3K2bm
cache:
  directories:
    - /home/travis/virtualenv
    - $HOME/.pip-cache/
