INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.staticfiles',

    'djcelery',
    'django_autologin',
    'django_keyerror',
    'django_slack',
    'django_yadt',
    'email_from_template',
    'staticfiles_dotd',
    'storages',
    'template_tests',
    'social.apps.django_app.default',

    'resultsrecorder.account',
    'resultsrecorder.debug',
    'resultsrecorder.elections',
    'resultsrecorder.results',
    'resultsrecorder.static',
    'resultsrecorder.utils',
)
