# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20160415_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='election',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
